## Functions by Michael Gableman for Coursera Course on R
## Created: 6-19-14
## makeCacheMatrix: takes a matrix and creates a list to be used with the cacheSolve function.
## cacheSolve: takes a list (generated by the makeCacheMatrix) and returns the inverse.

## Creates a list that can be used with the cacheSolve function to quickly find the inverse of the input matrix (x)

makeCacheMatrix <- function(x = matrix()) {
        inverse <- NULL  #sets the inital inverse to NULL
        set <- function(y){     #sets up a copy of the matrix as well as the inital inverse to a different enviroment
                x <<- y
                inverse <<- NULL
        }
        get <- function() x #creates a function that returns the matrix
        setinverse <- function(solve) inverse <<- solve #sets the inverse of the matrix
        getinverse <- function() inverse #returns the inverse of the matrix
        list(set = set, get = get, setinverse = setinverse, getinverse = getinverse) #creates the final list that contains all of the functions.
}


## calculates the inverse of a matrix based off of a list created from the makeCacheMatrix function

cacheSolve <- function(x, ...) {
        inverse <- x$getinverse() #gets cached inverse
        if(!is.null(inverse)){ #checks if inverse has already been found
                message("getting cached data")
                return(inverse)
        }
        #Calculates the inverse if no inverse has been found
        data <- x$get()
        inverse <- solve(data, ...)
        x$setinverse(inverse)
        inverse
}
